const topics = [
    {
      category: "Intelligent Computing",
      items: [
        "Artificial Intelligence",
        "Bio Inspired Computing",
        "Bioinformatics",
        "Computer Animation",
        "Computer Graphics",
        "Computer Vision",
        "Expert Systems",
        "Gaming and Animation",
        "Genetic Algorithms",
        "Image Processing",
        "Information Retrieval and Fusion",
        "Intelligent Control Systems",
        "Intelligent Systems",
        "Machine Learning",
        "Multimedia",
        "Natural Language Processing",
        "Pattern Recognition",
        "Robotics",
        "Soft Computing",
        "System Simulation",
        "Virtual Reality",
      ],
    },
    {
      category: "Systems Software",
      items: [
        "Compiler Design",
        "Computer System and Modeling",
        "Operating System",
        "Parallel and Distributed Computing",
        "Programming Languages",
        "System Software",
        "VLSI and Embedded Systems",
      ],
    },
    {
      category: "Data Communication and Networking",
      items: [
        "Agents",
        "Cloud Computing",
        "Computer Networks",
        "Cryptography",
        "Data Communications",
        "Grid Computing",
        "Information and Network Security",
        "Mobile Computing",
        "Network Management",
        "Services Oriented Architecture",
        "Storage Area Networks",
        "Wireless Communication",
      ],
    },
    {
      category: "Management Information System",
      items: [
        "Business Intelligence",
        "Computer & Information Science in Sports",
        "Computer in Education and Training",
        "Customer Relationship Management",
        "E-business Modeling",
        "E-commerce",
        "Economic Systems",
        "Enterprise Resource Planning",
        "Financial Systems",
        "Human Resource Management Systems",
        "Information Systems",
        "Just in Manufacturing",
        "Knowledge-Based Web Systems",
        "Management Information System",
        "Medical Informatics",
        "Supply Chain Management",
      ],
    },
    {
      category: "Blockchain",
      items: [
        "Theories of blockchain and distributed ledger technology",
        "Distributed consensus and fault tolerance mechanisms",
        "Security, privacy and trust of blockchain and distributed ledger technology",
        "Decentralization, scalability, and security tradeoff",
        "Performance analysis and optimization",
        "Simulation and performance evaluation techniques",
        "Smart contract and chain code",
        "Applications and services with blockchain and distributed ledger technology",
        "Protocols and algorithms based on blockchain",
        "Blockchain in the Internet of things (IoT)",
        "Blockchain in cyber physical systems",
        "Blockchain in social networking",
        "Blockchain in supply chain management",
        "Blockchain in agriculture",
        "Blockchain in connected and autonomous vehicles",
        "Blockchain in crowdsourcing and crowdsensing",
        "Blockchain in mobile cellular networks",
        "Blockchain in edge and cloud computing",
      ],
    },
    {
      category: "Database System",
      items: [
        "Big Data",
        "Data Engineering",
        "Data Mining",
        "Data Warehousing",
        "Database Management Systems",
        "Knowledge Discovery",
        "Web Mining",
      ],
    },
    {
      category: "Software Engineering",
      items: [
        "Agent Oriented Software Engineering",
        "Agile Software Engineering",
        "Component-Based Software Engineering",
        "Computer Aided Software Engineering",
        "Dependable Systems Design",
        "Software Architectures",
        "Software Dependability Evaluation",
        "Software Design Patterns",
        "Software Development Tools",
        "Software Economic",
        "Software Metrics",
        "Software Project Management",
        "Software Quality Assurance",
        "Software Reliability",
        "Software Reuse",
        "Software Reverse Engineering",
        "Software Testing",
        "Software Testing Tools",
        "Software Verification and Validation Techniques",
        "UML, OO Modeling",
      ],
    },
    {
      category: "Internet of Things",
      items: [
        "Next Generation Infrastructure for IOT",
        "Cloud Computing (IAAS, PAAS, SAAS) for IOT",
        "Big Data for IOT",
        "Open Platforms for IOT",
        "Wearable Devices for IOT",
        "Artificial Intelligence for IOT",
        "IOT-based Smart City Solutions",
        "IOT-based Smart Home",
        "IOT-based Smart Education Systems",
        "IOT-based Robots",
        "Security, Privacy, and Trust in IOT",
        "IOT Standards and Application Scenarios",
        "IOT-based Enterprise Management",
        "IOT-based Business Process Management",
        "IOT-based Auto Driving",
        "IOT-based Intelligent Manufacturing",
      ],
    },
    {
      category: "Security",
      items: [
        "Biometrics",
        "Computer Security",
        "Cryptography",
        "Data Encryption",
        "Digital Signature",
        "Digital Watermarking",
        "Forensics",
        "Fraud Control",
        "Information Security",
        "Intellectual Property Protection",
        "Network Security",
        "Optical Disc Copy Protection",
        "Phonography Control",
        "Rights Management Languages",
        "Software Cracking",
        "System Security",
        "Trusted Computing",
      ],
    },
  ];

  export default topics;